### PR TITLE
Availability check based on providers-common gem

### PR DESCRIPTION
**Pull request by slemrmartin**
**Issue** https://github.com/RedHatInsights/sources-api/issues/206

This PR moves Source#availability_check from AnsibleTower to providers-common. 

---

**Depends on**:
* [x] https://github.com/RedHatInsights/topological_inventory-providers-common/pull/25
* [x] https://github.com/RedHatInsights/topological_inventory-providers-common/pull/28
* [x] https://github.com/RedHatInsights/topological_inventory-openshift/pull/127
---

[TPINVTRY-944](https://projects.engineering.redhat.com/browse/TPINVTRY-944)

### CODE REVIEW

**Comment by slemrmartin** [comment]
specs are broken by https://github.com/RedHatInsights/topological_inventory-providers-common/pull/30 
..these specs should be moved to providers-common

**Comment by slemrmartin** [comment]
yes, but it will need more work to fix specs in this repo

**Comment by slemrmartin** [comment]
@syncrou what about fixing the rest of specs in separate PR because it's not related?

**Comment by gmcculloug** [comment]
@slemrmartin A separate PR is fine if the failures are unrelated, but we would we to wait on merging this PR until that test correction PR is ready to merge.

**Comment by lindgrenj6** [comment]
@slemrmartin I fixed the specs for this quick (no problem btw), since I had made similar changes when I added the clamp to default bytes PR. 

The specs were previously set up to count exact bytes from payloads etc, I changed them to see how many payload chunks it will get split into, that way we can change the multiplier (payload size) at will and the tests won't break. 

https://gist.github.com/lindgrenj6/4c495034bacfee913aeee0d7e5fc631d

**Comment by slemrmartin** [comment]
Thanks @lindgrenj6!

**Comment by slemrmartin** [comment]
Specs fixed in https://github.com/RedHatInsights/topological_inventory-openshift/pull/127,
patch applied in https://github.com/RedHatInsights/topological_inventory-providers-common/pull/35

**Pull request merged**
